/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worktask;

/**
 *
 * @author vitor
 */
public class Adicionatask extends javax.swing.JFrame {

    /**
     * Creates new form Adicionatask
     */
    public Adicionatask() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        grupoPrioridade = new javax.swing.ButtonGroup();
        grupoPrioridade.add(pbaixa);
        grupoPrioridade.add(pmedia);
        grupoPrioridade.add(palta);
        
        nometarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (nometarefa.getText().length() >= 27) {
                    evt.consume(); // Impede a digitação
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPrioridade = new javax.swing.ButtonGroup();
        salvatask = new javax.swing.JButton();
        voltatask = new javax.swing.JButton();
        nometarefa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudotask = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        selecionadata = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        labelDataSelecionada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelErro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pbaixa = new javax.swing.JRadioButton();
        pmedia = new javax.swing.JRadioButton();
        palta = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salvatask.setText("Salvar");
        salvatask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvataskActionPerformed(evt);
            }
        });

        voltatask.setText("Voltar");
        voltatask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltataskActionPerformed(evt);
            }
        });

        nometarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometarefaActionPerformed(evt);
            }
        });

        conteudotask.setColumns(20);
        conteudotask.setRows(5);
        jScrollPane1.setViewportView(conteudotask);

        jLabel1.setText("Texto da Tarefa");

        selecionadata.setValue(0);
        selecionadata.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selecionadataStateChanged(evt);
            }
        });

        jLabel2.setText("Escolha o dia");

        jLabel3.setText("Nome da Tarefa");

        labelErro.setText("...");

        jLabel4.setText("Prioridades");

        pbaixa.setText("Baixa");

        pmedia.setText("Média");

        palta.setText("Alta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(salvatask, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(voltatask, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelErro)
                        .addGap(0, 572, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pmedia)
                            .addComponent(pbaixa)
                            .addComponent(palta)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel2))
                                .addComponent(labelDataSelecionada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selecionadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nometarefa)
                                .addGap(163, 163, 163)))
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nometarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDataSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(pbaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pmedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvatask, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltatask, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(labelErro)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltataskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltataskActionPerformed
        Menutarefa menu = new Menutarefa();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltataskActionPerformed

    private void nometarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometarefaActionPerformed

    private void selecionadataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selecionadataStateChanged

      int diasSelecionados = selecionadata.getValue();

   
      java.util.Calendar cal = java.util.Calendar.getInstance();

       
      cal.add(java.util.Calendar.DAY_OF_MONTH, diasSelecionados);

     
      java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
      String dataFormatada = sdf.format(cal.getTime());

      labelDataSelecionada.setText("Data de execução: " + dataFormatada);

    }//GEN-LAST:event_selecionadataStateChanged
    
    
    private void salvataskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvataskActionPerformed
        try {
                
                String nomeTarefa = nometarefa.getText();
                String conteudo = conteudotask.getText();
                String dataInsercao = "2025-05-22"; // capture a data atual formatada
                int diasSelecionados = selecionadata.getValue();

                // Calcula a data executada adicionando os dias ao hoje
                java.util.Calendar cal = java.util.Calendar.getInstance();
                cal.add(java.util.Calendar.DAY_OF_MONTH, diasSelecionados);

                // Formata a data para dd/MM/yyyy
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                String dataExecucao = sdf.format(cal.getTime());

                // Captura a prioridade selecionada
                String prioridade = "";
                if (pbaixa.isSelected()) {
                    prioridade = "Baixa";
                } else if (pmedia.isSelected()) {
                    prioridade = "Média";
                } else if (palta.isSelected()) {
                    prioridade = "Alta";
                }

                // Monta o JSON manualmente
                String jsonInputString = String.format(
                    "{\"nomeTarefa\":\"%s\", \"conteudo\":\"%s\", \"dataInsercao\":\"%s\", \"dataExecucao\":\"%s\", \"prioridade\":\"%s\"}",
                    nomeTarefa, conteudo, dataInsercao, dataExecucao, prioridade);

                // Cria a conexão HTTP para POST
                java.net.URL url = new java.net.URL("http://localhost:8080/tarefas");
                java.net.HttpURLConnection con = (java.net.HttpURLConnection) url.openConnection();
                con.setRequestMethod("POST");
                con.setRequestProperty("Content-Type", "application/json; utf-8");
                con.setRequestProperty("Accept", "application/json");
                con.setDoOutput(true);

                // Envia o JSON no corpo da requisição
                try(java.io.OutputStream os = con.getOutputStream()) {
                    byte[] input = jsonInputString.getBytes("utf-8");
                    os.write(input, 0, input.length);
                }

                // Lê a resposta da API
                int code = con.getResponseCode();
                java.io.BufferedReader br;
                if (code == 200 || code == 201) {
                    br = new java.io.BufferedReader(new java.io.InputStreamReader(con.getInputStream(), "utf-8"));
                } else {
                    br = new java.io.BufferedReader(new java.io.InputStreamReader(con.getErrorStream(), "utf-8"));
                }
                StringBuilder response = new StringBuilder();
                String responseLine = null;
                while ((responseLine = br.readLine()) != null) {
                    response.append(responseLine.trim());
                }

                // Exibe o retorno se foi sucesso ou ERRO.
                labelErro.setText(response.toString());

            } catch (Exception ex) {
                labelErro.setText("Erro: " + ex.getMessage());
            }
    }//GEN-LAST:event_salvataskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adicionatask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adicionatask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adicionatask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adicionatask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adicionatask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea conteudotask;
    private javax.swing.ButtonGroup grupoPrioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataSelecionada;
    private javax.swing.JLabel labelErro;
    private javax.swing.JTextField nometarefa;
    private javax.swing.JRadioButton palta;
    private javax.swing.JRadioButton pbaixa;
    private javax.swing.JRadioButton pmedia;
    private javax.swing.JButton salvatask;
    private javax.swing.JSlider selecionadata;
    private javax.swing.JButton voltatask;
    // End of variables declaration//GEN-END:variables
}
