/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worktask;

/**
 *
 * @author vitor
 */
import javax.swing.text.MaskFormatter;
import javax.swing.JFormattedTextField;

public class Edittask extends javax.swing.JFrame {

    /**
     * Creates new form Edittask
     */
    public Edittask() {
        initComponents();
        setLocationRelativeTo(null);
        
        grupoPrioridade = new javax.swing.ButtonGroup();
        grupoPrioridade.add(pbaixa);
        grupoPrioridade.add(pmedia);
        grupoPrioridade.add(palta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPrioridade = new javax.swing.ButtonGroup();
        backtask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        datatask = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pbaixa = new javax.swing.JRadioButton();
        pmedia = new javax.swing.JRadioButton();
        palta = new javax.swing.JRadioButton();
        nometarefa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudotask = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        selecionadata = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        labelDataSelecionada = new javax.swing.JLabel();
        alttask = new javax.swing.JButton();
        pesqtask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backtask.setBackground(new java.awt.Color(255, 255, 255));
        backtask.setForeground(new java.awt.Color(0, 0, 0));
        backtask.setText("Voltar");
        backtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtaskActionPerformed(evt);
            }
        });

        jLabel1.setText("Data da tarefa");

        datatask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datataskActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome da Tarefa");

        jLabel4.setText("Prioridades");

        pbaixa.setText("Baixa");

        pmedia.setText("Média");

        palta.setText("Alta");

        nometarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometarefaActionPerformed(evt);
            }
        });

        conteudotask.setColumns(20);
        conteudotask.setRows(5);
        jScrollPane1.setViewportView(conteudotask);

        jLabel2.setText("Texto da Tarefa");

        selecionadata.setValue(0);
        selecionadata.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selecionadataStateChanged(evt);
            }
        });

        jLabel5.setText("Escolha o dia");

        alttask.setBackground(new java.awt.Color(51, 51, 255));
        alttask.setForeground(new java.awt.Color(255, 255, 255));
        alttask.setText("Alterar");

        pesqtask.setText("Pesquisar");
        pesqtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqtaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pmedia)
                            .addComponent(pbaixa)
                            .addComponent(palta)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel5))
                                .addComponent(labelDataSelecionada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selecionadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datatask, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesqtask))
                            .addComponent(jLabel1)))
                    .addComponent(nometarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alttask, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(backtask, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datatask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqtask))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nometarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDataSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(pbaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pmedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backtask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alttask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtaskActionPerformed
      Menutarefa tarefa = new Menutarefa();
      tarefa.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_backtaskActionPerformed
    
    
    private void datataskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datataskActionPerformed
     
 
        
    }//GEN-LAST:event_datataskActionPerformed

    private void nometarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometarefaActionPerformed

    private void selecionadataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selecionadataStateChanged

        int diasSelecionados = selecionadata.getValue();

        java.util.Calendar cal = java.util.Calendar.getInstance();

        cal.add(java.util.Calendar.DAY_OF_MONTH, diasSelecionados);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = sdf.format(cal.getTime());

        labelDataSelecionada.setText("Data de execução: " + dataFormatada);
    }//GEN-LAST:event_selecionadataStateChanged

    private void pesqtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqtaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesqtaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edittask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edittask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edittask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edittask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edittask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alttask;
    private javax.swing.JButton backtask;
    private javax.swing.JTextArea conteudotask;
    private javax.swing.JTextField datatask;
    private javax.swing.ButtonGroup grupoPrioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataSelecionada;
    private javax.swing.JTextField nometarefa;
    private javax.swing.JRadioButton palta;
    private javax.swing.JRadioButton pbaixa;
    private javax.swing.JButton pesqtask;
    private javax.swing.JRadioButton pmedia;
    private javax.swing.JSlider selecionadata;
    // End of variables declaration//GEN-END:variables
}
